#!/bin/bash

# Script to be used with Matugen to generate Material You colors for Waybar
# This script should be called after Matugen generates its colors
# Place this in your dotfiles and configure Matugen to run it after generation

# Source the colors generated by pywal/Matugen
source ~/.cache/wal/colors.sh

# Ensure cache directory exists
mkdir -p ~/.cache/wal

# Generate the waybar color file using the template and pywal/Matugen colors
cp ~/.config/wal/templates/colors-waybar.css ~/.cache/wal/colors-waybar.css

# Replace placeholders with actual colors
sed -i "s|{color0}|$color0|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color1}|$color1|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color2}|$color2|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color3}|$color3|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color4}|$color4|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color5}|$color5|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color6}|$color6|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color7}|$color7|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color8}|$color8|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color9}|$color9|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color10}|$color10|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color11}|$color11|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color12}|$color12|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color13}|$color13|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color14}|$color14|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{color15}|$color15|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{background}|$background|g" ~/.cache/wal/colors-waybar.css
sed -i "s|{foreground}|$foreground|g" ~/.cache/wal/colors-waybar.css

# Fix the double curly braces (they're used as escape characters in the template)
sed -i "s|{{|{|g" ~/.cache/wal/colors-waybar.css
sed -i "s|}}|}|g" ~/.cache/wal/colors-waybar.css

echo "Waybar Material You colors have been generated!"

# Restart Waybar to apply changes (optional, uncomment if needed)
# killall -SIGUSR2 waybar