# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F3FAFF
background         #1F2025
cursor             #93B0DB

active_tab_foreground     #1F2025
active_tab_background     #F3FAFF
inactive_tab_foreground   #F3FAFF
inactive_tab_background   #1F2025

active_border_color   #F3FAFF
inactive_border_color #1F2025
bell_border_color     #0E182B

color0      #45464C
color1		#0E182B
color2		#254D8A
color3		#254D8A
color4		#5378A7
color5		#728CB1
color6		#A6B4BE
color7		#E6EFF6
color8		#A1A7AC
color9		#13203A
color10		#3266B8
color11		#3266B8
color12		#6FA0DF
color13		#97BBEB
color14		#DDF0FE
color15		#E6EFF6
